### PR TITLE
Add SCAPv2 reference material

### PR DESCRIPTION
**Pull request by davaya**

### CODE REVIEW

**Comment by dlemire60** [comment]
I'm happy to have these added, but I'm a bit confused: the PR adds links to the README file but doesn't appear to also include adding the files being linked into the repo. Is something missing?

**Comment by davaya** [comment]
I've put in a "bug report" to GitHub on that, but since I'm a personal subscriber I don't get official support.  Perhaps OCA can open a real ticket.

When you use GitHub web to create a PR, it creates a "patch-1" branch, opens an editor, and has the "Attach files by dragging & dropping, selecting or pasting them" message.  I edited the README, dragged the three files, and GitHub uploaded them.  But it didn't put the files in the repo!!  (They're in the repo "files" folder, but the folder is invisible, like hidden files in Windows.)

If you click on the links in the README they work, but the files are invisible when looking at commits.  That's clearly a bug.  For now, go ahead and merge the README PR (after verifying that the links work), and we'll have to figure out how to make the "files" folder visible, like "docs" and all other folders.

**Comment by dlemire60** [comment]
If I select Rich Diff view the links work, and now have three newly downloaded PDFs.  So I'll merge the PR.

I'll get Chet Ensign to take a look at this, since OASIS seems big enough to get attention from GH.

**Comment by OASIS-OP-Admin** [comment]
Thank you for the compliment. I doubt we're 'big' on GitHub's scale. But I'll see if we can't find out something about this.

**Comment by davaya** [comment]
Thanks for merging.  I created a new [PR #14](https://github.com/opencybersecurityalliance/PACE/pull/14) to put the reference material in the normal location.

**Pull request merged**
