### PR TITLE
charter from PGB

### PR DESCRIPTION
**Pull request by sparrell**
copy charter from PDB email archives to make readily accessible

### CODE REVIEW

**Comment by sparrell** [comment]
I propose this PR be discussed at next weekly PACE meeting

**Comment by dlemire60** [comment]
As the content is what was approved by the OCA PBG I don't have any suggested changes to it. I'm not sure it makes sense to bury this in a sub-folder of `docs`, where it's likely to be the only file. It seems to me it should either be in the root folder or the `docs` folder, but nothing deeper than that.

EDIT: it appears that links in the original project proposal document (e.g., to the SACM Architecture ID) were lost in conversion to Markdown.

**Comment by adammontville** [comment]
@sparrell, yes, we should discuss. In fact, I'd like to make rolling through open PRs standard process for each weekly meeting, in addition to rolling through open issues/tickets. 

@dlemire60, I like the charter being at the root level.

**Comment by sparrell** [comment]
@dlemire60 - the PR has been modified to rename the file to PACE_charter.md and move it to the top directory.

**Comment by adammontville** [comment]
Rename `PACE_charter.md` to `charter.md`

**Pull request merged**
