### PR TITLE
Uses cases to input SBOMs into PACE

### PR DESCRIPTION
**Pull request by sparrell**

### CODE REVIEW

**Comment by sparrell** [comment]
discussed at 18-Apr-2022 PACE meeting:
- the internet access should not be over the integration bus - remove that pic
- change the direct internet access line to dotted and note that it's interface is outside scope of PACE. Different systems could do it differently and it would not affect interworking
- Change so no direct PAR write interface. It still should go thru PCS on way in and thru PES on way out

**Comment by davaya** [comment]
Diagrams "CollectSbomFromDevice" and "CollectSbomFromDevice2" are intended to illustrate a difference between Component and Monolithic PACE.  But to the external world PACE must still be an OpenC2 Consumer (for interactions with DM) or OpenC2 Producer (for interactions with ComponentX).  In Device2, suggest moving green PAC API to dotted PACE boundary, analogous to PCS boundary in Device, and terminate the green DM interface.  The red SBOM interface also terminates at the PACE boundary but not inside the PAC API.

Also suggest using a different color for unspecified/internal interfaces - not red for the URL retrieval and not blue for the internal, perhaps dotted purple or brown, to avoid confusion with blue PAR API.

**Comment by dlemire60** [comment]
I concur w/ @davaya's comments about the Device2 figure.

**Comment by dlemire60** [comment]
Two comments:
1) I don't see what change was made to the figure in commit 6ccf00b (labeled "nit").
2) The comment from @davaya that I supported has not been addressed and I think it's very important to fix that problem. The connection to ComponentX has _nothing_ to do with the PAC AP, and they need to be separated. I'm amendable to approving the PR with the caveat that this will be fixed.

**Pull request merged**
