### PR TITLE
need code of conduct

### PR DESCRIPTION
**Pull request by sparrell**

### CODE REVIEW

**Comment by dlemire60** [comment]
The draft you've provided looks good to me and seems very reasonable. Others will have to fill in the WHATGOESHERE blanks.  

I'd not hear of the Contributor Covenant before. Is what you have here close enough that it should include their badge?

**Comment by JasonKeirstead** [comment]
I don't disagree that PACE can have it's own COC, but it should at least refer to the OCA COC (here https://github.com/opencybersecurityalliance/oasis-open-project)

Note that one is also somewhat of a stub, that refers to the contributors covenant. We need to take action to update it.

**Comment by claurau** [comment]
I can work with you on the CoC if that would help.

**Comment by adammontville** [comment]
Open question we can discuss: If there is the OCA CoC, do we need to have a PACE CoC?

**Comment by sparrell** [comment]
Since OCA adopted a CoC, and we are a subproject, I propose to close this PR and adopt PR #27  instead

**Comment by sparrell** [comment]
This has been superseded and should be rejected, closed and/or moved to done.

**Pull request closed without merging**
